.TH MQTT_INSPECTOR 1 "February 2026" "tts-tester 0.1.0"
.SH NAME
tts-tester \- Text-to-speech engine comparison tool
.SH SYNOPSIS
.B tts-tester
.SH DESCRIPTION
.B tts-tester
is a GTK4 application for LText-to-speech engine comparison tool.
.SH OPTIONS
None currently supported.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
.SH SEE ALSO
.BR gtk4 (7)
